# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bdaa569d-d63d-4179-bb4d-ee260b781176";
      fsType = "ext4";
    };
    
 # Mounting other drives into a folder without Gvfs
 
# fileSystems."/mt/games" =
#   { device = "/dev/disk/by-uuid/0016441616440EDA";
#      fsType = "ntfs";
#    };
    
    
#  fileSystems."/mt/programme" =
#    { device = "/dev/disk/by-uuid/501E25411E252208";
#      fsType = "ntfs";
#    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CF47-6E1C";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/87f3e156-1ee3-47a3-a9b6-95d0670348f2"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
